---
type: spine

spine:
  defaults:
    platform: vEOS-lab
    # loopback_ipv4_pool: 198.18.248.224/27
    loopback_ipv4_pool: 198.18.248.224/27
    bgp_as: 65100

  nodes:
    - name: SPN1-FAB1
      id: 1
      mgmt_ip: 192.168.1.150/24
    - name: SPN2-FAB1
      id: 2
      mgmt_ip: 192.168.1.151/24
