---
### group_vars/endpoints.yml

routers:
  - name: Testpoint1
    adapters:
      - endpoint_ports: [ G0/0, G0/1 ]
        switch_ports: [ Ethernet3, Ethernet3 ]
        switches: [ DLF1-FAB1, DLF2-FAB1 ]
        vlans: 10,20,1100,1110
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel Testpoint190
          mode: active

  - name: Testpoint2
    adapters:
      - endpoint_ports: [ G0/0, G0/1 ]
        switch_ports: [ Ethernet3, Ethernet3 ]
        switches: [ DLF3-FAB1, DLF4-FAB1 ]
        vlans: 10,20,1100,1110
        native_vlan: 4092
        mode: trunk
        spanning_tree_portfast: edge
        port_channel:
          description: PortChannel Testpoint191
          mode: active
