---
tenants:
  - name: TENANT2
    mac_vrf_vni_base: 20000
    vrfs:
      - name: PROD
        vrf_vni: 110
        vtep_diagnostic:
          loopback: 10
          loopback_ip_range: 10.255.255.64/27
        svis:
          - id: 210
            name: VLAN210_PROD
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          - id: 220
            name: VLAN220_PROD
            enabled: true
            ip_address_virtual: 10.10.20.1/24
      - name: DEV
        vrf_vni: 111
        vtep_diagnostic:
          loopback: 11
          loopback_ip_range: 10.255.255.96/27
        svis:
          - id: 310
            name: VLAN310_DEV
            enabled: true
            ip_address_virtual: 10.10.110.1/24
          - id: 320
            name: VLAN320_DEV
            enabled: true
            ip_address_virtual: 10.10.120.1/24

    l2vlans:
      - id: 1100
        name: L2_VLAN1100
      - id: 1110
        name: L2_VLAN1110
