---
type: spine

spine:
  defaults:
    platform: vEOS-lab
    # loopback_ipv4_pool: 198.18.255.224/27
    loopback_ipv4_pool: 198.18.250.224/27
    bgp_as: 65200

  nodes:
    - name: SPN1-FAB2
      id: 11
      mgmt_ip: 192.168.1.160/24
    - name: SPN2-FAB2
      id: 12
      mgmt_ip: 192.168.1.161/24