---
### group_vars/CISCO_FABRIC.yml

ansible_connection: ansible.netcommon.httpapi
ansible_network_os: nxos
ansible_user: admin
ansible_password: admin
ansible_become: true
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false

fabric_name: CISCO_FABRIC