---
tenants:
  - name: TENANT1
    mac_vrf_vni_base: 10000
    vrfs:
      - name: PROD
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 10
          loopback_ip_range: 10.255.255.0/27
        svis:
          - id: 10
            name: VLAN10_PROD
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 20
            name: VLAN20_PROD
            enabled: true
            ip_address_virtual: 10.1.20.1/24
      - name: DEV
        vrf_vni: 11
        vtep_diagnostic:
          loopback: 11
          loopback_ip_range: 10.255.255.32/27
        svis:
          - id: 110
            name: VLAN110_DEV
            enabled: true
            ip_address_virtual: 10.1.110.1/24
          - id: 120
            name: VLAN120_DEV
            enabled: true
            ip_address_virtual: 10.1.120.1/24

    l2vlans:
      - id: 1100
        name: L2_VLAN1100
         
      - id: 1110
        name: L2_VLAN1110
